%{
    #include <stdio.h>
    #include <string>
    using namespace std;
    int yylex();
    void yyerror(string msg);
%}

%token TOKEN_ID
%token KEY_INT
%token KEY_IF
%token KEY_FOR
%token LIT_ZEROS

%%

program: ldecl
    ;

ldecl: dec ';' ldecl
    |
    ;

dec: vardec
    | fdec
    ;

vardec: KEY_INT TOKEN_ID '=' LIT_ZEROS
    ;

fdec: KEY_INT TOKEN_ID '(' ')' cmdl
    ;

cmdl: cmd cmdl
    |
    ;

cmd: TOKEN_ID '=' expr
    | KEY_IF expr cmd
    |
    ;

expr: TOKEN_ID
      | LIT_ZEROS
      | expr '+' expr
      ;

%%

void yyerror(string msg){
    fprintf(stderr, "Erro de sintaxe\n");
    exit(3); // indispensavel
}